### ISSUE TITLE
Should I create a hosted version of this app?

### ISSUE THREAD

**Issue by forsbergplustwo** [forsbergplustwo/partner-metrics-for-shopify#1]
Welcome everyone. If you'd like to see a hosted version of this application, so you can simply acess it on the web, login and leave all the technical stuff to me, then just add a +1 comment below :)

**Comment by pjc** [comment]
+1 

Also, I see refunds mentioned in the screenshot. Can we give refunds to app customers? I've always used PayPal for that until now.

**Comment by barranger** [comment]
+1

**Comment by bakura10** [comment]
+1

**Comment by forsbergplustwo** [comment]
Hey @pjc @barranger @bakura10 ! This is now available at www.partnermetrics.io 😎 Enjoy!
