### ISSUE TITLE
Using Baremetrics Analytics API

### ISSUE THREAD

**Issue by sergey-alekseev** [forsbergplustwo/partner-metrics-for-shopify#11]
You [mentioned](https://github.com/forsbergplustwo/partner-metrics-for-shopify/commit/5c55a11bc5ab29de973dbf2fa0f2ad4df532f771#diff-04c6e90faac2675aa89e2176d2eec7d8R117) baremetrics.com in README.md. Have you ever considered using their [Analytics API](https://baremetrics.com/features/api)?

**Comment by forsbergplustwo** [comment]
The Analytics API didn't exist when I originally created this.. so it just wasn't an option. Would have loved to simply build an integration to that instead.. but now I have this and it get's the job done :)
