### ISSUE TITLE
packaging issues

### ISSUE THREAD

**Issue by resistorsoftware** [forsbergplustwo/partner-metrics-for-shopify#3]
I use Ruby 2.2.1

cloned the repo. killed the Gemfile.lock and bundled with the newer Ruby. created my db in postgresql. 

ran the command rails s

rails s
Warning: You're using Rubygems 2.0.14 with Spring. Upgrade to at least Rubygems 2.1.0 and run `gem pristine --all` for better startup performance.
Your Ruby version is 2.0.0, but your Gemfile specified 2.2.1

I never use Rails, but I am an expert with Ruby and therefore I am requesting your opinion on what this mess is? My rubygem version is 2.4.6 well beyond anything at 2.0.14, is Spring not some Java crap? and huh?

I thought Rails was a no-brainer? I am obviously out of the loop here... Any tips?

**Comment by forsbergplustwo** [comment]
Hi David,

Sounds like you need to switch over to the newer Ruby you put into the gemfile.. could be wrong. If you use RVM try:

rvm use ruby 2.2.1

Then try again.

Just heading out for dinner now, but let me know how it goes and I'll dig some more into it later tonight.

Cheers!

**Comment by resistorsoftware** [comment]
I got it working with a long winded:  rails server

Nice job! It made some sense right off the hop. I get it that it is
monthly... would be nice to have a date range picker. Not sure about some
of the metrics, for example I have one of my hundred or so Apps with 1400
subscribers... but this App shows 788 for all Apps? Not sure where that
number comes from.

I will dig into the guts sometime to discover...

Thanks for your effort on this. Should appeal to a certain crowd for sure.
I like the fact that all my metrics are rising. Was not always so in the
early days.

Dave

**Comment by forsbergplustwo** [comment]
Glad you got it working Dave, and thanks for the feedback! Date ranges could be useful. In case you didn't notice you can look at the data in Monthly, Weekly, Daily timeranges using the drop down by the date already.. it's enough for me at this stage, but of course people are welcome to add/improve on this.

Regarding the app subscriber count, I had the same 1st reaction. Keep in mind however that a lot of people install our apps, but then jump ship before they accept/activate the monthly charge (you'll see this in the Event History on your apps in the partner site).. so over time the number in the partner site will get inflated with a bunch of installs that are not paying you, and never bothered to uninstall. The metric in this app counts how many unique shops paid you during the selected period.

My Shopify site shows me around 1000 active users on one of my apps, however only about 650 of those are paying me monthly. Monthly being 30 days: https://docs.shopify.com/manual/settings/account/invoices#app-fees

The 650 paying also fits a lot better with the amount that I get paid out each month for it, based on my subscription price.

All the main calculations are done in the ```app/models/payment_history.rb``` file, mainly calculated by day... and then on the views either summed or averaged over the period you are viewing (monthly, weekly daily). Please do take a look at it and let me know if you think the calculations could use some more work.

Good stuff on the metrics going up.. if only we could have that all the time! ;)
